add basename to URLs
basename is needed when using get_queryset() instead of queryset. Otherwise,
this error is raised:

AssertionError: `basename` argument not specified,
and could not automatically determine the name from the viewset,
as it does not have a `.queryset` attribute.